module.exports = {
	RECEIVED_GROUPS: "RECEIVED_GROUPS",
	RECEIVED_GROUP: "RECEIVED_GROUP",
	REMOVED_GROUP: "REMOVED_GROUP",
	JOINED_GROUP: "JOINED_GROUP",
	GROUPS_DISTANCE_FETCHED: "GROUPS_DISTANCE_FETCHED"
};